services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true

  report:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    ports:
      - "9323:9323"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - BASE_URL=http://app:3000
    command: ["npx", "playwright", "show-report", "--host", "0.0.0.0"]
    depends_on:
      - app
